// Comprehensive Windows path input matrix, shared by the test suite and the
// node:path coverage probe so both exercise identical inputs.

export const MATRIX: readonly string[] = [
  // drive-absolute
  "C:\\foo\\bar",
  "C:\\foo\\..\\bar",
  "C:\\foo\\.\\bar",
  "C:\\foo\\\\bar",
  "C:\\foo\\bar\\",
  "C:\\..\\..\\foo",
  "C:\\a\\b\\c\\..\\..\\..\\..\\d",
  "C:\\",
  "C:\\a",
  "C:\\file.txt",
  "C:\\Users\\name\\file.txt",
  "C:\\CON",
  "C:\\.",
  "C:\\dir\\.env",
  "C:\\dir\\README",
  "c:\\foo\\bar",
  "C:/foo",
  "C:/a/b",
  "C:/a/../b",
  "C:/",
  // drive-relative (no root slash)
  "C:foo\\bar",
  "C:foo\\..\\bar",
  "C:",
  "C:a",
  "C:a\\b",
  "c:foo\\bar",
  // rooted, current drive
  "\\foo\\bar",
  "\\foo",
  "/foo",
  "\\..\\..\\foo",
  // relative
  "foo\\bar\\baz",
  "foo",
  "foo.txt",
  "a\\b\\c.js",
  "foo\\..\\..\\bar",
  "a\\..\\..\\..\\b",
  "foo/bar",
  "a/b/c",
  "a\\b\\\\c",
  "./foo",
  "..\\foo",
  // dot / empty / root-only
  ".",
  "..",
  "..\\..\\..",
  "",
  " ",
  "\\",
  "/",
  // UNC
  "\\\\server\\share\\foo",
  "\\\\server\\share",
  "\\\\server\\share\\",
  "\\\\server\\share\\a\\b",
  "\\\\server\\share\\a\\..\\b",
  "\\\\server\\share\\a\\b.txt",
  "\\\\server\\share\\dir\\sub\\file.tar.gz",
  "\\\\server\\share\\a\\",
  "//server/share",
  "//server/share/foo",
  "\\\\server\\",
  "\\\\server",
  // extended-length (\\?\), must stay verbatim
  "\\\\?\\C:\\foo\\..\\bar",
  "\\\\?\\C:\\a\\b",
  "\\\\?\\C:\\",
  "\\\\?\\C:",
  "\\\\?\\C:\\a\\.\\b\\\\c",
  "\\\\?\\C:\\a\\b.ts",
  "\\\\?\\foo",
  "\\\\?\\UNC\\server\\share\\foo",
  "\\\\?\\UNC\\server\\share",
  "\\\\?\\Volume{xxxx}\\a\\b",
  "\\\\?\\GLOBALROOT\\Device\\X",
  "//?/C:/a/b",
  "//?/C:/a/../b",
  // device (\\.\), slashed (the device namespace tolerates '/')
  "\\\\.\\C:\\foo\\..\\bar",
  "\\\\.\\COM1",
  "\\\\.\\C:\\a\\b",
  "\\\\.\\pipe\\mypipe",
  "\\\\.\\PhysicalDrive0",
  "//./COM1",
  // mixed separators
  "C:/foo\\bar",
  "C:\\foo/bar/",
  "foo/bar\\baz",
  "C:\\a/b\\c.ts",
  // names / extensions
  "CON",
  "NUL",
  "aux.txt",
  "file.",
  "a..",
  ".env",
  ".env.local",
  "a.b.c",
  "archive.tar.gz",
  "README",
  // POSIX-specific normalize / dirname edges
  "//foo",
  "foo/../",
  "a/b/../../",
  "/foo/bar/../",
  "//",
  "///foo",
];

export const PAIRS: ReadonlyArray<readonly [string, string]> = [
  ["C:\\a", "b"],
  ["C:\\a", "\\b"],
  ["C:\\a", "C:b"],
  ["C:\\a", "D:\\b"],
  ["C:\\a\\b", "..\\c"],
  ["C:\\foo", "C:\\foo\\bar\\baz"],
  ["C:/Foo/Bar", "C:/foo/baz"],
  ["c:\\project\\src", "C:\\Project\\src\\utils"],
  ["\\\\server\\share\\a", "b"],
  ["\\\\server\\share\\a", "\\\\server\\share\\a\\b"],
  ["\\\\?\\C:\\a", "b"],
  ["foo\\bar", "baz"],
  [".", "foo"],
  ["/foo", "bar"],
  ["C:\\a\\b\\c", "C:\\a\\d"],
];

// `basename(path, suffix)` exercises the suffix-stripping branch (the no-suffix
// form is covered by MATRIX).
export const BASENAME_SUFFIX: ReadonlyArray<readonly [string, string]> = [
  ["C:\\a\\file.txt", ".txt"],
  ["C:\\a\\file.txt", ".js"],
  ["C:\\a\\file.txt", "file.txt"],
  ["/a/b.ts", ".ts"],
  ["a/b/c.js", ".js"],
  ["archive.tar.gz", ".gz"],
  ["archive.tar.gz", ".tar.gz"],
  ["C:\\a\\b", "b"],
  ["C:\\a\\b", "xyz"],
  ["foo", "foo"],
  [".env", ".env"],
  ["README", ""],
  ["C:\\a\\", "\\"],
  ["file.", "."],
  ["ab", "b"],
  ["/a/", "a"],
  ["///", "/"],
  ["/", "/"],
  ["//foo//", "foo"],
  ["abc", "c"],
  ["/a/b/", "b"],
];

// Many-arg `join`: empty-arg filtering, UNC joins, multi-segment.
export const JOIN_ARGS: ReadonlyArray<readonly string[]> = [
  [],
  [""],
  ["", ""],
  ["C:\\a", "", "b"],
  ["C:\\a", "b", "c", "d"],
  ["\\\\server\\share", "a", "b"],
  ["a", "..", "b"],
  ["C:\\", "a"],
  ["/", "a"],
  ["C:\\a\\", "\\b"],
  ["foo", "C:\\bar"],
  ["", "C:\\a"],
  [".", ".", "."],
  ["\\\\server\\share\\", "", "x"],
  ["C:", "a"],
  ["//s/sh", "a"],
  ["\\\\", "a"],
  ["\\\\\\", "a"],
  ["//foo", "bar"],
  ["///", "x"],
  ["//", "a", "b"],
  ["/", "/a"],
];

// Many-arg `resolve`: drive accumulation, root resets, drive-relative segments.
export const RESOLVE_ARGS: ReadonlyArray<readonly string[]> = [
  [], // zero args resolves to the real cwd (flipped on a Windows host)
  ["C:\\a", "b", "c"],
  ["C:\\a", "D:\\b", "c"],
  ["\\\\server\\share", "a", "..", "b"],
  ["C:\\a", "..", "..", ".."],
  ["C:base", "sub"],
  ["C:\\a", "C:b"],
  ["C:\\a", "/x", "y"],
  ["a", "b"],
  ["C:\\a\\b", "..", ".\\c"],
  ["D:\\x", "C:y"],
  ["C:\\a", "d:\\b"],
  ["C:\\a", ""],
  ["C:"],
  ["C:foo"],
  [""],
  ["/a", ""],
  ["C:\\a", "C:"],
  ["c:/x", "C:\\y"],
];

// Diverse `relative` pairs: same, cross-root, prefix relationships, case, UNC.
export const RELATIVE_PAIRS: ReadonlyArray<readonly [string, string]> = [
  ["C:\\a", "C:\\a"],
  ["C:\\a\\b", "C:\\a"],
  ["C:\\a", "C:\\a\\b\\c"],
  ["C:\\a", "D:\\a"],
  ["C:\\foo\\bar", "C:\\foo\\baz"],
  ["C:\\", "C:\\a\\b"],
  ["C:\\a\\b\\c", "C:\\a"],
  ["C:\\a", "C:\\A\\b"],
  ["c:\\x\\y", "C:\\x\\z"],
  ["C:\\foo", "C:\\foobar"],
  ["\\\\s\\sh\\a", "\\\\s\\sh\\b"],
  ["\\\\s\\sh", "\\\\t\\sh"],
  ["\\\\s\\sh\\a\\b", "\\\\s\\sh\\a"],
  ["foo\\bar", "foo\\baz"],
  ["C:\\a", "c:\\a"],
  ["C:\\foo\\bar", "C:\\"],
  ["C:\\", "C:\\foo"],
  ["\\\\s\\sh\\a\\b\\c", "\\\\s\\sh\\a"],
  // posix-style pairs (exercise posix.relative root/base branches)
  ["/foo/bar/baz", "/foo/bar"],
  ["/", "/foo"],
  ["/foo/bar", "/"],
  ["/a", "/a"],
  ["/foo/bar", "/foo/baz"],
  ["/a/b/c", "/a"],
];

// `format` inputs: dir-vs-root and base-vs-name/ext branches.
export const FORMAT_INPUTS: ReadonlyArray<Record<string, string>> = [
  { dir: "C:/a", base: "b.ts" },
  { root: "C:/", base: "b.ts" },
  { name: "b", ext: ".ts" },
  { dir: "C:/a", name: "b", ext: ".ts" },
  { base: "b.ts" },
  { root: "C:/", name: "b", ext: ".ts" },
  { dir: "//s/sh", base: "x" },
  {},
  { dir: "C:/a", base: "" },
  { name: "b", ext: "ts" },
  { root: "C:/", name: "b" },
  { dir: "", base: "x" },
  { name: "b" },
];
